# Generated by Django 3.2.2 on 2021-05-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Home', 'Home'), ('Car', 'Car'), ('Taxes', 'Taxes'), ('Food', 'Food'), ('Others', 'Others')], default='Others', max_length=50)),
                ('income', models.PositiveIntegerField()),
                ('expenses', models.PositiveIntegerField()),
            ],
        ),
    ]
